/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/M8hjbKZ5Uh6
 */
import Link from "next/link";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import Image from "next/image";

export function Landingpage() {
  return (
    <div className="flex flex-col  max-w-md bg-slate-400 mx-auto">
      <div className="h-14 flex items-center bg-teal-400"></div>
      {/* <main className="flex-1">
        <section className="w-full py-12 md:py-24 lg:py-32 xl:py-48">
          <div className="container flex flex-col items-center justify-center px-4 space-y-4 md:px-6">
            <div className="space-y-2 text-center">
              <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl">
                We make your dreams come true
              </h1>
              <p className="max-w-[700px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Let us help you achieve your goals with our professional and
                dedicated team.
              </p>
            </div>
            <form className="flex flex-col gap-2 min-[400px]:flex-row">
              <Input
                className="max-w-md flex-1"
                placeholder="Enter your email"
                type="email"
              />
              <Button type="submit">Sign Up</Button>
            </form>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800">
          <div className="container grid items-center gap-6 px-4 text-center md:px-6 lg:gap-10">
            <div className="space-y-3">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
                Our Services
              </h2>
              <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                We offer a wide range of services to meet your needs.
              </p>
            </div>
            <div className="mx-auto grid max-w-5xl items-center gap-6 lg:grid-cols-3 lg:gap-12">
              <div className="space-y-2">
                <h3 className="text-2xl font-bold tracking-tighter">
                  Web Design
                </h3>
                <p className="text-gray-500 dark:text-gray-400">
                  We create beautiful and functional websites that help you
                  stand out online.
                </p>
              </div>
              <div className="space-y-2">
                <h3 className="text-2xl font-bold tracking-tighter">
                  Digital Marketing
                </h3>
                <p className="text-gray-500 dark:text-gray-400">
                  Reach your audience with our digital marketing strategies that
                  drive results.
                </p>
              </div>
              <div className="space-y-2">
                <h3 className="text-2xl font-bold tracking-tighter">
                  Mobile Apps
                </h3>
                <p className="text-gray-500 dark:text-gray-400">
                  Engage your customers with a custom mobile app designed for
                  your business.
                </p>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container grid items-center gap-6 px-4 text-center md:px-6 lg:gap-10">
            <div className="space-y-3">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
                Contact Us
              </h2>
              <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Ready to get started? Contact us to discuss your project.
              </p>
            </div>
            <div className="mx-auto w-full max-w-sm space-y-2">
              <form className="grid grid-cols-2 gap-2">
                <Input placeholder="Name" type="text" />
                <Input placeholder="Email" type="email" />
                <Input
                  className="col-span-2"
                  placeholder="Subject"
                  type="text"
                />
                <Textarea className="col-span-2" placeholder="Message" />
                <Button type="submit">Submit</Button>
              </form>
            </div>
          </div>
        </section>
      </main> */}
      {/* <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
        <p className="text-xs text-gray-500 dark:text-gray-400">
          © 2024 Acme Inc. All rights reserved.
        </p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            Terms of Service
          </Link>
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            Privacy
          </Link>
        </nav>
      </footer> */}
    </div>
  );
}

function MountainIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  );
}
